package com.ddook.ddak.board.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.springframework.data.annotation.Id;

/**
 * 게시물 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Article implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시물고유번호. */
	@Id
	private Long articleId;

	/** 게시물번호. */
	private int articleNumber;

	/** 게시판번호. */
	private int boardId;

	/** 카테고리아이디. */
	private int categoryId;

	/** 공지. */
	private String notice;

	/** 숨김여부. */
	private String hidden;

	/** 제목. */
	private String title;

	/** 게시물태그. */
	private String tags;

	/** 회원번호. */
	private int mId;

	/** 회원닉네임. */
	private String mNickname;

	/** 유저아이콘. */
	private String mIcon;

	/** ip주소. */
	private String ipAddress;

	/** 조회수. */
	private int readCount;

	/** 추천수. */
	private int recommCount;

	/** 첨부파일수. */
	private int fileCount;

	/** 댓글수. */
	private int commentCount;

	/** 신고수. */
	private int reportCount;

	/** 입력일. */
	private LocalDateTime regDate;

	/** 수정일. */
	private LocalDateTime updateDate;

	public Long getArticleId() {
		return articleId;
	}

	public void setArticleId(Long articleId) {
		this.articleId = articleId;
	}

	public int getArticleNumber() {
		return articleNumber;
	}

	public void setArticleNumber(int articleNumber) {
		this.articleNumber = articleNumber;
	}

	public int getBoardId() {
		return boardId;
	}

	public void setBoardId(int boardId) {
		this.boardId = boardId;
	}

	public int getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public String getNotice() {
		return notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

	public String getHidden() {
		return hidden;
	}

	public void setHidden(String hidden) {
		this.hidden = hidden;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTags() {
		return tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	public int getmId() {
		return mId;
	}

	public void setmId(int mId) {
		this.mId = mId;
	}

	public String getmNickname() {
		return mNickname;
	}

	public void setmNickname(String mNickname) {
		this.mNickname = mNickname;
	}

	public String getmIcon() {
		return mIcon;
	}

	public void setmIcon(String mIcon) {
		this.mIcon = mIcon;
	}

	public String getIpAddress() {
		return ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public int getReadCount() {
		return readCount;
	}

	public void setReadCount(int readCount) {
		this.readCount = readCount;
	}

	public int getRecommCount() {
		return recommCount;
	}

	public void setRecommCount(int recommCount) {
		this.recommCount = recommCount;
	}

	public int getFileCount() {
		return fileCount;
	}

	public void setFileCount(int fileCount) {
		this.fileCount = fileCount;
	}

	public int getCommentCount() {
		return commentCount;
	}

	public void setCommentCount(int commentCount) {
		this.commentCount = commentCount;
	}

	public int getReportCount() {
		return reportCount;
	}

	public void setReportCount(int reportCount) {
		this.reportCount = reportCount;
	}

	public LocalDateTime getRegDate() {
		return regDate;
	}

	public void setRegDate(LocalDateTime regDate) {
		this.regDate = regDate;
	}

	public LocalDateTime getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(LocalDateTime updateDate) {
		this.updateDate = updateDate;
	}


}
