package com.ddook.ddak.board.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * 게시글카테고리 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(
	name="board_category",
	uniqueConstraints={
		@UniqueConstraint(
			columnNames={"boardId","categoryId"}
		)
	}
)
public class BoardCategories implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시판. */
	private int boardId;

	/** 카테고리아이디. */
	@Id @GeneratedValue(strategy = GenerationType.AUTO) 
	private int categoryId;

	/** 카테고리 이름 */
	private String cateName;
	
	/**숨김여부**/
	private String hidden;

	/** 정렬 */
	private int sort;

	/**
	 * 생성자.
	 */
	public BoardCategories() {
	}

	public int getBoardId() {
		return boardId;
	}

	public void setBoardId(int boardId) {
		this.boardId = boardId;
	}

	public int getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public String getCateName() {
		return cateName;
	}

	public void setCateName(String cateName) {
		this.cateName = cateName;
	}

	public int getSort() {
		return sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	public String getHidden() {
		return hidden;
	}

	public void setHidden(String hidden) {
		this.hidden = hidden;
	}

}
