package com.ddook.ddak.board.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * 게시판 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
public class Boards implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** board_id. */
	@Id @GeneratedValue(strategy = GenerationType.AUTO) 
	private int boardId;	
	/** 게시판 물리적 이름. */
	@Column(unique=true)
	private String boardName;	
	/** 속성값. */
	private String boardAttr;

	public Boards(){}

	public Boards(int boardId, String boardName, String boardAttr) {
		super();
		this.boardId = boardId;
		this.boardName = boardName;
		this.boardAttr = boardAttr;
	}
	
	public int getBoardId() {
		return boardId;
	}

	public void setBoardId(int boardId) {
		this.boardId = boardId;
	}

	public String getBoardName() {
		return boardName;
	}

	public void setBoardName(String boardName) {
		this.boardName = boardName;
	}

	public String getBoardAttr() {
		return boardAttr;
	}

	public void setBoardAttr(String boardAttr) {
		this.boardAttr = boardAttr;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Boards other = (Boards) obj;
		if (boardId == 0) {
			if (other.boardId != 0) {
				return false;
			}
		} else if (boardId != other.boardId) {
			return false;
		}
		return true;
	}

}
